### PR TITLE
Replace proxy settings with an enum.

### PR DESCRIPTION
**Pull request by deepy**
This replaces the proxy setting with an enum containing:

- `SMART` (previous `true`)
- `FORCED` (always apply)
- `OFF` (previous `false`)

### CODE REVIEW

**Comment by bsautel** [comment]
That's good!

I improved the proxy documentation to explain the three different modes.

I am also wondering if we don't have a naming issue. The property is named `useGradleProxySettings` and the enum `ProxySetting`. Should not the enum end with an `s`? My english is quite poor and I am not sure about that, but it sounds like the two names should be consistent. What do you think about that?

Some integration tests are broken, but it sounds like it is not because of those changes, it's because of the Node.js upgrade and an remaining hardcoded npm version that I fixed in the master branch.

**Comment by deepy** [comment]
Ooh, good catch, and we should probably rename `useGradleProxySettings` to something else as well.
Maybe `inheritGradleProxySettings` or `nodeProxySettings`

**Comment by bsautel** [comment]
Ok for renaming the property. I would say `nodeProxySettings` or even `proxySettings`.

**Review by bsautel — APPROVED** [review]
That looks very good!

**Pull request merged**
