### PR TITLE
#166 Handling Power PC architecture

### PR DESCRIPTION
**Pull request by akatona84**

### CODE REVIEW

**Comment by akatona84** [comment]
It would fix #166

**Review by deepy — APPROVED** [review]

**Comment by akatona84** [comment]
Thanks @deepy for merging. Do you have any idea when a new version will be released with this fix?

**Comment by deepy** [comment]
Hi @akatona84, sorry about the delay, I'm home and sick and have varying levels of energy, I've pushed 3.1.0 now so this should be arriving to a plugin portal near you within the hour

**Comment by akatona84** [comment]
Thanks! I hope u r okay now, or at least better :)

I was able to test it on ppc and seems to be working as expected.

**Pull request merged**
