### PR TITLE
sunset jcenter

### PR DESCRIPTION
**Pull request by cdietrich**
sunset jcenter
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
i dont know how the actual publishing works? is it still through jcenter? if yes we might have to do something there too

**Comment by deepy** [comment]
Current plugin publishing is to the Gradle Plugin Portal, I was working on publishing to Bintray for snapshots but ended up with a lot of duplicated configuration and with a confusing UI as well, it never really took off.

Which makes me wonder if we should start considering publishing snapshots on maven central

**Comment by cdietrich** [comment]
maybe https://oss.sonatype.org/#view-repositories;snapshots~browsestorage would be sufficient for snapshots

**Comment by bsautel** [comment]
Thanks @cdietrich! I did not know that jCenter was going to be disappear, I just come to learn it. I think that this pull request can be merged.

**Comment by bsautel** [comment]
The Javadoc publication is broken since this pull request was merged.

We did not see it in the build actions since the one that published the Javadoc does not run when pull requests are submitted and this is specifically this task that is broken. The reason is that some dependencies of the dokka plugin (dokka is the tool that generates the Koltin API documentation) are only available in the jcenter repository and not in the maven central one.

I tried to upgrade to the latest dokka version (big step from 0.10.0 to 1.4.20) but it still requires some artifacts from jcenter. For now I enabled jcenter again and hope Jetbrains will solve that soon.

**Comment by cdietrich** [comment]
@bsautel is it one of these: https://plugins.gradle.org/search?term=dokka
if yes we could do the kotlin equivalent of this
https://github.com/xtext/xtext-gradle-plugin/blob/2cdb00110f8101a6f2b87906c505bf742b4ef9da/build.gradle#L4

**Comment by cdietrich** [comment]
newer gralde version also seem to have this one https://github.com/gradle/gradle/blob/60063b9d8d8c5f587895d9115ff8787e6009e9c2/subprojects/core-api/src/main/java/org/gradle/api/artifacts/dsl/RepositoryHandler.java#L90

**Comment by bsautel** [comment]
Not sure I understand what you mean. The problem is not about how to declare the repository. It is that the dokka plugin requires some dokka jars at runtime and they are only available in jcenter (and not Maven Central).

Here is the error we had with the dokka 0.10.1 version:
```
> Task :dokka FAILED
FAILURE: Build failed with an exception.


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
* What went wrong:
Use '--warning-mode all' to show the individual deprecation warnings.
Execution failed for task ':dokka'.
See https://docs.gradle.org/6.8.1/userguide/command_line_interface.html#sec:command_line_warnings
> Could not resolve all files for configuration ':dokkaRuntime'.
   > Could not find org.jetbrains.dokka:dokka-fatjar:0.10.1.
     Searched in the following locations:
1 actionable task: 1 executed
       - https://repo.maven.apache.org/maven2/org/jetbrains/dokka/dokka-fatjar/0.10.1/dokka-fatjar-0.10.1.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
```

And after dokka 1.4.20 upgrade we get this error:
```
> Task :dokkaJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dokkaJavadoc'.
> Could not resolve all files for configuration ':dokkaJavadocPlugin'.
   > Could not find org.jetbrains.dokka:javadoc-plugin:1.4.20.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/jetbrains/dokka/javadoc-plugin/1.4.20/javadoc-plugin-1.4.20.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 519ms
```

Note that it sounds like there is no intermediary version between 0.10.x and 1.4.x.

**Comment by bsautel** [comment]
Sorry @cdietrich, I just come to read your comment in my commit and now I understand what you meant and you are right, it works! All the artifacts that are missing in the Maven central repository are available in the Gradle plugin portal one,  so adding it where you suggested works.

Thanks a lot for your help, and sorry for my misunderstanding. Thanks to you we no longer depend on jcenter!

**Comment by deepy** [comment]
Gradle plugin portal does fallback to jcenter and maven central, so not sure that's going to be more of a solution, but at least it feels better than having `jcenter()` in there

Aaaaand unfortunately we can't upgrade dokka 😅 https://github.com/Kotlin/dokka/issues/1692 https://github.com/node-gradle/gradle-node-plugin/issues/113#issuecomment-756041532

I should've extracted that into an issue

**Comment by bsautel** [comment]
Oops, I did not know about that. Ok, I downgrade to 0.10.0.
And I did not know that the Gradle plugin portal fallbacks to jcenter. I also revert the replacement of jcenter by Gradle plugin portal.

**Pull request merged**
