### PR TITLE
Change execOverrides to Action<ExecSpec>

### LINKED ISSUE #72: Groovy DSL issue with execOverrides and nodeModulesOutputFilter properties
With version 2.2.1 a task similar to this works fine, however with 2.2.2 I'm getting errors related to the `execOverrides`:

`java.io.File cannot be cast to kotlin.Unit` for the first override
`java.io.FileOutputStream cannot be cast to kotlin.Unit` for the second

```
task foo(type: NodeTask) {
    def inputFiles = fileTree('src/main/resources').include("foo.yaml")
    def outputFile = file("$buildDir/bar.yaml")
    def workingDir = file("$buildDir/tmp")
    dependsOn npmInstall
    script = file('node_modules/somenodebinary')
    args = [
      ...
    ]
    inputs.files inputFiles
    outputs.file outputFile
    execOverrides {
      it.workingDir = workingDir
      it.standardOutput = new FileOutputStream(outputFile)
    }
    doFirst {
      ...
    }
  }
```

### PR DESCRIPTION
**Pull request by deepy**
This hopefully fixes #72

### CODE REVIEW

**Comment by bsautel** [comment]
@deepy, I merged your `execoverrides` branch with the branch I am currently working on in order to get faster tests execution. This also provides the Kotlin DSL test I added.

I thought I already tested the `execOverrides` option in integration tests but it was not the case, so I added some tests. Without your fix, it indeed does not work using the Groovy DSL. I can confirm you that this fix solves the issue for the Groovy DSL. But now we have the Kotlin DSL test, it appears that your change breaks it. It is the reason why the build of this branch is broken.

Also, for some reason (which may be related to the Groovy DSL magic), your fix does not work with Gradle 5.0. I don't know exactly as of which version it works, but it works with Gradle 5.6.4. I could workaround this by skipping this test in Gradle 5.

**Comment by bsautel** [comment]
I found a way to improve the compatibility with the Kotlin DSL but it still does not work with Gradle 5.0 (and probably other versions before Gradle 5.6.4).

**Comment by bsautel** [comment]
I close this pull request, I integrated it to #90.

**Comment by deepy** [comment]
With Gradle 6 released I'm not sure we want to put too much effort into supporting 5.0.
5.6 yes, for sure, but 5.0 has questionable value.

**Comment by bsautel** [comment]
Yes. I read that Spring Boot 2.3 which will be released soon will support only Gradle 5.6 and 6. We can probably do the same thing.

**Pull request closed without merging**
