### PR TITLE
Run integration tests with multiple Gradle versions

### PR DESCRIPTION
**Pull request by bsautel**
This pull request changes the test execution flow in order to get them executed on multiple Gradle versions (`5.0` and `5.6.2` for now) as requested in issue #4 .

It works but it dramatically increases the tests execution time. What else could we expect?

Do you think running with the lowest and highest supported version is a good choice? Do you think some tests would require to be also executed on specific intermediate versions?

Also, I could not get the iteration (the fact of running multiple times the same method with different configurations) name work. It prints the Gradle version in the Gradle output in order to easily know which version corresponds to iterations `0` and `1` (default naming).

I can adapt the Spock extension according to your feedback.

### CODE REVIEW

**Comment by deepy** [comment]
This looks great! Thanks for yet another good PR!
For now earliest 5 and latest 5 is a good target, but this will really shine when Gradle 6 is released :-)

And we can cut down the total runtime by running the tests in parallel. This melts the MacBook I tested it on but has a positive effect on the total runtime.

I tried with `maxParallelForks = Runtime.runtime.availableProcessors().intdiv(2) ?: 1` locally, which gave me a total build time of 7m52s compared to 5m42s from yesterday.
And by splitting the tests into smaller classes we can quickly (although a bit dirty) make it faster.
(`NpmTask`/`NpmRule` each being 25% of the total time, this could probably also be fixed by running the tests in a specific order but jUnit suites elude me.)

(quick and dirty table with the results from my laptop)

```
44 tests        12m4.05s duration
---------------------------------
NpmInstall_integTest  3m25.19s
NpmRule_integTest     3m17.21s
NpmSetupTaskTest      2.366s
NpmTaskTest           0.232s
NpmTask_integTest     2m41.48s
NpxTaskTest           0.498s
NpxTask_integTest     2m37.08s```

**Comment by deepy** [comment]
Sadly enough, the `maxParallelForks` snippet does nothing for travis builds, although 12 minutes for a full build isn't that terrible

**Comment by bsautel** [comment]
Running tests in parallel is a good idea.
It does not make any difference on Travis probably because it runs on a single core server but on a multi-core computer that can make a big difference.

When you talk about splitting test classes, you mean that splitting them will enable to benefit more from parallelism because tests of the same specification cannot be run in parallel?

And what kind of change would you expect from reordering `NpmTask` and `NpmRule` tests?

**Comment by deepy** [comment]
Yeah at least before spock 2, tests in the same class can't be run in parallel, so if we split the test classes the total runtime per class will be lower, making sure that if the slowest one is run last it won't have as big impact on a parallel run.

Which wouldn't be a problem if we could make sure that the slowest test is run first and the fastest one last since that way we can make use of the additional runs. Though I can't see a good way to do this with spock and even if we split one of the slow tests from `NpmTask_integTest` into another class, perhaps a `NpmTask_sunny_integTest` it only makes the build less than a minute faster.

**Comment by bsautel** [comment]
Ok, I see what you mean. That would take less time but as you said this would not divide the execution time by two.

Even if it does not change anything in the CI build, we should probably enable parallel execution in master, it would at least help us by speeding up feedback while working.

Yesterday I fixed a regression I introduced in the latest version. Sorry for that. I had to change the `YarnExecRunner` which had no integration test so I added them. They are exactly the same as `NpmTask` tests for now. I don't know Yarn very well and I don't know whether it's relevant but it will be better than nothing. Sadly, it still increased the build time.

**Comment by bsautel** [comment]
I just pushed a commit in the branch `skip-node-download-in-integration-tests` that stops downloading and installing Node.js at each integration test.

On my laptop the tests execution takes about 1 minute less (about 7 minutes instead of 8) without parallel test execution.

It makes the assumption that `node`, `npm` and `yarn` are globally installed and available in the `PATH`. Do you think we can make this assumption? In this case, I'll mention those requirements in the project readme file.

Notice that in addition to speeding up the build, it adds integration tests in the no download configuration (personally I use the plugin this way). It sounds like this configuration was not really tested, there are a few tests in the `Setup_integTest` spec that test the setup task which no download, but they do not try to execute anything, so we are not sure it works. And as far as I know, there were no tests that ensure the `npm`, `npx` and `yarn` tasks work in this configuration.

**Comment by deepy** [comment]
Hmm, this is a tricky one.

On one hand it's nice that the tests require very little from the host computer, but on the other hand it's worrisome that we have no tests for the "not downloaded" case.

I guess what we probably should do on travis is curl/wget an npm before running then setup an `IvyRepository` pointing to that, that way we wouldn't have to redownload it all the time and could keep the logic the same and not require globally installed tools.

And then also add tests for verifying that the no-download setup works. Which would require us to add node to travis.

That'd give us faster tests, keep the requirements for new contributors low, and test all the paths.

What do you think?

**Comment by deepy** [comment]
oh hey, travis apparently has two cores [virtualisation-environment-vs-operating-system](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system)

**Comment by bsautel** [comment]
I see what you mean.

I am wondering which of downloading or installing Node.js takes more time. I assume it depends on the network speed. Caching the download will speed up the build only if the download takes a significant amount of time.

I don't know how the setup task works exactly, but it sounds like it declares the Node.js archive download website as an Ivy repository. I assume it then asks Gradle to download it from the repository. If it's right, it may take advantage of Gradle's repository caching? I don't know exactly how Ivy works but I believe it works this way for Maven repositories.
If my assumption is true, there is already a local cache and caching it ourselves would not change anything, except we would not really test the download from the default Node.js repository.

And how can we test the plugin in the not downloaded case (I mean using the global installed tools) if we only skip the download but still install it locally?

Do you think installing Node.js, NPM and Yarn are some hard requirements that would prevent people from contributing?

And last think, I read again your parallel test configuration and I saw it divides the cores number by two. On a dual core host, it sets it to 1 (= no parallelism). This may explain why this does not speed up the build on Travis?

**Comment by deepy** [comment]
I haven't looked at it, but if node was cached between tests I'd expect the tests to be faster, since unpacking a 13M archive should be pretty fast. 

Now in normal operations in should cache, though in the specific case of the tests this might not be shared between test classes (which would explain why they take a long time).

We'd still have to have some specific tests to make sure that running it works no matter if you're the plugin to download it or install it globally.

Installing node/npm/yarn locally just to develop a plugin might not be a hard requirement, but personally I see it as a nice to have since previously I didn't have the tools installed locally at all and that's where I entered from. Although lately I have a much larger stake in this so I've had to install it all locally anyways ;-)

With that said, if it's harder to maintain it this way then there's really no reason not go with a globally installed, but if it's not too much work it'd be nice to have it as a toggle in case someone don't want to install it globally (or if they can't, though I can't think of any case where that'd be an issue)

As for Travis, I'll add in a property for overriding that and set it to 2 in `.travis-ci.yml`, hopefully that speeds it up. I initially thought they just had a single core available so that's a nice surprise :-)

**Comment by bsautel** [comment]
I don't have much time to investigate this these days, but I did a very simple experiment. I ran the `NpmTask` integration tests offline. They work.

This probably means that Node.js is not downloaded at each test execution. You are right, I would not expect the archive extraction to take so much time but it sounds like it is what happens.

I should have a little more time next week to investigate that.

Ok for overriding the parallelism configuration in the Travis file. But why would we not use all the cores? I believe that when you use the `--parallel` Gradle option to execute tasks in parallel, by default it uses all the available cores.

Have a nice week-end and take care of you!

**Pull request merged**
