### PR TITLE
issue 21. add nodeRepository only if there's no existing one in the b…

### PR DESCRIPTION
**Pull request by sine-loco**
Just illustration of how is checked whether to create node repo or not. 
No tests yet :)

### CODE REVIEW

**Comment by deepy** [comment]
I like the approach, but would the user's repository really have the same url?

Maybe it'd make more sense to only add a repo if `distBaseUrl` is not null?
That'd allow corporate users to prevent the creation of a repository they can't even reach.

**Comment by sine-loco** [comment]
> I like the approach, but would the user's repository really have the same url?
Well, if user deliberately configures a node repo with credentials, it surely will have the same URL :)

> Maybe it'd make more sense to only add a repo if `distBaseUrl` is not null?
I'm not sure that I understand you correctly :(
NodeExtension#distBaseUrl has a default value. The only way for it to be null is to be set to null by user. If user intentionally tries to break their build - well, so be it, I cannot prevent

**Comment by deepy** [comment]
Sorry I was a bit brief, I'll clarify my suggestion:

We always add the repository, unless the `distBaseUrl` has been set to null.

The non-firewalled users would leave `distBaseUrl` as default (or set to a mirror)
The corporate-firewalled users would set `distBaseUrl` to `null` and add their own repository in `build.gradle`.

This way we can "disable" adding the repository by setting it to null so that if your repository is nexus.yourcompany.local you don't have to add a repository in both build.gradle **and** `distBaseUrl`

**Comment by sine-loco** [comment]
> Sorry I was a bit brief, I'll clarify my suggestion:
> 
> We always add the repository, unless the `distBaseUrl` has been set to null.
> 
> The non-firewalled users would leave `distBaseUrl` as default (or set to a mirror)
> The corporate-firewalled users would set `distBaseUrl` to `null` and add their own repository in `build.gradle`.
> 
> This way we can "disable" adding the repository by setting it to null so that if your repository is nexus.yourcompany.local you don't have to add a repository in both build.gradle **and** `distBaseUrl`

Yes, now I got your point, thanks :)
The fact is I implemented scheme with dictBaseUrl and existing repo check when I first created this issue - when all other repos were removed during node download :)
In current condition your suggestion seems reasonable - there's indeed no need for double configuration :)

**Comment by sine-loco** [comment]
Changed repo creation logic.
I'm a bit tight on time, so tests are still absent :(

**Comment by deepy** [comment]
@sine-loco this is available on master now, although with version 2.0.0 (that has been released) you should be able to add your own repo and if the artifact is found there the task will use that one :-)

**Pull request merged**
