### PR TITLE
Fixed symlink for npx

### PR DESCRIPTION
**Pull request by nakul02**
Fixes the `npx` symlink so that `NpxTask` works correctly (on mac)

### CODE REVIEW

**Comment by nakul02** [comment]
Ping @bsautel - could you please take a look?

**Comment by bsautel** [comment]
Thanks @nakul02 for this contribution.

Just to improve my knowledge regarding this part of the code (I am a recent contributor on this plugin and I don't know very well the install mechanism), in which case are you facing this issue? Why is the symlink broken?

It should probably be interesting to add some tests to ensure this works as expecting, but I need to reproduce it first.

**Comment by nakul02** [comment]
I was using node v12.13.0 (on Mac Mojave) when I noticed this problem.
My build.gradle had this:
```
node {
  version = '12.13.0'
  distBaseUrl = 'https://nodejs.org/dist'
  download = true
}
```

The gradle node plugin downloads and unpacks the node dist into `.gradle/nodejs/node-v12.13.0-darwin-x64/lib/node_modules/npm/`

It also symlinks `.gradle/nodejs/node-v12.13.0-darwin-x64/lib/node_modules/npm/bin/npm` to `.gradle/nodejs/node-v12.13.0-darwin-x64/lib/node_modules/npm/bin/npm-cli.js` (even though i think it should symlink to `.gradle/nodejs/node-v12.13.0-darwin-x64/lib/node_modules/npm/bin/npm`. 
But it did not do the same for `npx`. This is what my PR does.

The NpxTask uses this symlink.

**Comment by bsautel** [comment]
Thanks for these explanations!

It remains me one question. The `NpxTask` code (it's exactly the same for `NpmTask`) seems to use the global `npx` command when configured to use the global NodeJS installation (`download = false`, by default). When using the downloaded NodeJS installation, it uses directly the `npx-cli.js` file (either the one installed locally of the one provided with NodeJs).

How did you notice this issue? Did you have an error? Do you know where this local `npx` file is executed?

Sorry for my questions and thanks again for your contributions!

**Comment by bsautel** [comment]
Thanks for your answer. I now understand correctly what happens.

It can also use the `npx` command if none of the `npx-cli.js` files are found (even if `download` is `true`). And when `download` is `true`, it does not use the global `npx` command but the local one, this happens [here](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/main/groovy/com/moowork/gradle/node/variant/VariantBuilder.groovy#L86).

I will try to investigate more this issue. It sounds like it does not look for the `npm-cli.js` file in the right directory. Is it normal? Is it only for macOS? If yes, is it because the macOS package does not have the same layout as the Linux one for instance? Is the symbolic link fix really necessary or was it introduced as a workaround of another bug?

**Comment by nakul02** [comment]
I noticed the issue when i tried to add a `NpxTask` to our project. It would always succeed but produce no output or error file. Then I saw that `.gradle/nodejs/node-v12.13.0-darwin-x64/lib/node_modules/npm/bin/npx` is an empty file.

Hope my contribution helps.
Do you know when you are going to release a new version?

**Comment by bsautel** [comment]
Ok, I also noticed that the `npm` and `npx` files are empty in the Node.js bundle. This is probably the reason why it is fixed in the plugin code.

I just come to push some commits that improve the tests regarding the Node.js, npm and yarn versions used. I will continue to investigate this in order to add a test that ensures the symlink are fixed correctly, but for that I need to reproduce the issue in a simple use case.

I think we are ready to release a new version. @deepy, could you release a new version? I can create the change log if you want.

**Comment by bsautel** [comment]
It sounds like this is now tested as a side effect of another change.

It stopped using some specific npm versions in all our integration tests for performance reasons. Specifying a npm version requires it to be downloaded and takes some time. I just let it when we test that this specific version is really used.

Thanks to this change, we are now in the same situation as you, Node.js is downloaded and the npm version is not set. If I remove the symbolic link fix, several tests no longer pass.

And it sounds like the symbolic links are broken because the Gradle's `tarTree` method does not support symbolic links, it is the reason why we get some empty files.

**Comment by bsautel** [comment]
Ok, nice. I prepared the release notes in the change log file.

I called it 2.2.0 since it contains at least one new feature (the ability to filter the node_modules output directory) in addition to multiple bug fixes.

**Comment by deepy** [comment]
I think we might need to split the integration tests further, I had to go to sleep before my build finished, so I'll do the release today instead

**Comment by bsautel** [comment]
You are right, the integration tests take too much time. I created issue #45 to discuss about that.

**Comment by deepy** [comment]
2.2.0 has been released

**Comment by bsautel** [comment]
Great! Thanks @deepy!

**Pull request merged**
