### PR TITLE
Added support for pnpm

### LINKED ISSUE #67: Consider supporting pnpm
**pnpm** is a fast, disk space efficient package manager relying on hard links and symlinks to save only **one copy** of a module/version **regardless of how many projects you have using the same version of a module or library**. Read more about it at https://pnpm.js.org/

As someone who experiments a lot, I have dozens of projects using same versions of libs/modules and the disk space used across all node_modules directories for all those projects adds up fast. 

It would be nice to add support for pnpm through a config flag so that developers could choose to make use of it in local builds.
Thanks!

### PR DESCRIPTION
**Pull request by DreierF**
Based on https://github.com/node-gradle/gradle-node-plugin/pull/89 by @langrp
Fixes #67 

- Fixed the merge conflicts
- Removed `PnpxTask` as pnpx has been [deprecated as of pnpm 6](https://pnpm.io/6.x/pnpx-cli) and does no longer appear in the pnpm 7 docs
- Reenabled the tests for windows as the [corresponding issue](https://github.com/pnpm/pnpm/issues/948) has been fixed in the meantime
- Adjusted the tests to take configuration avoidance into account

The tests for MacOS and Windows are passing, but for some reason the tests on Ubuntu seem to [hang](https://github.com/DreierF/gradle-node-plugin/runs/6825602587?check_suite_focus=true) without producing any error in the end. 

Any idea what could go wrong there?

### CODE REVIEW

**Comment by deepy** [comment]
They could also genuinely be timing out, the big suite takes **a lot** of time

**Comment by deepy** [comment]
I'm going to regret merging this since the pnpm tests [are the 3 slowest test classes](https://scans.gradle.com/s/hi2r37noe74x6/tests/overview?toggled=WyI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUucG5wbS50YXNrLnBucG10YXNrX2ludGVndGVzdC0xMyIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5wbnBtLnRhc2sucG5wbXJ1bGVfaW50ZWd0ZXN0LTE0IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnBucG0udGFzay5wbnBtaW5zdGFsbF9pbnRlZ3Rlc3QtMjQiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUubnBtLnRhc2subnB4dGFza19pbnRlZ3Rlc3QtNSIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5ucG0udGFzay5ucG10YXNrX2ludGVndGVzdC0xMSIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5ucG0udGFzay5ucG1pbnN0YWxsX2ludGVndGVzdC0xNyIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS55YXJuLnRhc2sueWFybmluc3RhbGxfaW50ZWd0ZXN0LTYiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUueWFybi50YXNrLnlhcm50YXNrX2ludGVndGVzdC05IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnRhc2subm9kZXRhc2tfaW50ZWd0ZXN0LTI3IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnlhcm4udGFzay55YXJucHJveHlfaW50ZWd0ZXN0LTEwIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLmtvdGxpbmRzbF9pbnRlZ3Rlc3QtMzEiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUubnBtLnRhc2subnBtcnVsZV9pbnRlZ3Rlc3QtMTUiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUubnBtLnRhc2subnBtcHJveHlfaW50ZWd0ZXN0LTIxIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLm5wbS50YXNrLm5wbV9pbnRlZ3Rlc3QtOCIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS55YXJuLnRhc2sueWFybnJ1bGVfaW50ZWd0ZXN0LTEyIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnlhcm4udGFzay55YXJuX2ludGVndGVzdC03IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnBhY2thZ2Vqc29uZXh0ZW5zaW9uX2ludGVndGVzdC00IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnN5c3RlbXZlcnNpb25faW50ZWd0ZXN0LTIyIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnBhY2thZ2Vqc29uZXh0ZW5zaW9udGVzdC0yMyIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5ucG0udGFzay5ucHh0YXNrdGVzdC0zIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnlhcm4udGFzay55YXJuc2V0dXB0YXNrdGVzdC0yIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnlhcm4udGFzay55YXJudGFza3Rlc3QtMSIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5wbnBtLnRhc2sucG5wbXRhc2t0ZXN0LTI1IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLm5wbS50YXNrLm5wbXNldHVwdGFza3Rlc3QtMTgiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUudmFyaWFudC52YXJpYW50Y29tcHV0ZXJ0ZXN0LTI5IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLnRhc2subm9kZXRhc2t0ZXN0LTMwIiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLm5wbS5wcm94eS5ucG1wcm94eXRlc3QtMCIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5ucG0udGFzay5ucG10YXNrdGVzdC0xOSIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5ub2RlcGx1Z2ludGVzdC0yNiIsIjp0ZXN0LTAtY29tLmdpdGh1Yi5ncmFkbGUubm9kZS5ucG0udGFzay5ucG1pbnN0YWxsdGFza3Rlc3QtMTYiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUudXRpbC5wbGF0Zm9ybWhlbHBlcnRlc3QtMzIiLCI6dGVzdC0wLWNvbS5naXRodWIuZ3JhZGxlLm5vZGUucG5wbS50YXNrLnBucG1zZXR1cHRhc2t0ZXN0LTI4IiwiOnRlc3QtMC1jb20uZ2l0aHViLmdyYWRsZS5ub2RlLm5vZGVleHRlbnNpb250ZXN0LTIwIl0) 🥲
I'll have to rework the tests and/or the test setup before I can make a release

**Comment by FortinFred** [comment]
Please consider updating documentation.

It's unclear if a pnpm_install task is now available.

**Comment by deepy** [comment]
@FortinFred there's a `pnpmInstall` to match, best bet currently is to look at the pnpm integtests
Opening an issue for this would be best though as closed issues/PRs easily disappear in notifications

**Pull request merged**
